project:
  type: website
  output-dir: docs
website:
  title: "Celâl Güney"
  site-url: "https://jeylal.github.io/celalguney/"
  navbar:
    left:
      - about.qmd
      - text: CV
        file: CV.qmd 
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: envelope-fill
        href: mailto:celal.98@outlook.com
      - text: "Research"
        file: research.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Content"
        menu: 
        - text: "Post"
          file: index.qmd
        - text: "Economics"
          file: https://jeylal.github.io/heterodox-economics/
        - text: "RE Geneva Workshops"
          file: reWorkshops.qmd


format:
  html:
    theme: 
      light: flatly
      dark: darkly

editor: visual

